apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcgoonch-headless-deployment
  labels:
    app: grpcgoonch-headless
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grpcgoonch-headless
  template:
    metadata:
      labels:
        app: grpcgoonch-headless
    spec:
      containers:
      - name: grpcgoonch-headless
        image: thaigoonch/grpcgoonch-headless:1.3
        ports:
        - name: serviceport
          containerPort: 9000
        resources:
          requests:
            memory: "350Mi"
          limits:
            cpu: "0.70"
            memory: "350Mi"
      nodeSelector:
        goonchrole: "server"
---
kind: Service
apiVersion: v1
metadata:
  name: grpcgoonch-headless-service
  labels:
    app: grpcgoonch-headless
spec:
  selector:
    app: grpcgoonch-headless
  type: ClusterIP
  clusterIP: None
  ports:
  - name: serviceport
    port: 80
    targetPort: 9000
  - name: prometheusport
    port: 9092
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grpcgoonch-headless-servicemonitor
  namespace: default
  labels:
    app: grpcgoonch-headless
    release: prometheus
spec:
  selector:
    matchLabels:
      app: grpcgoonch-headless # target service
  endpoints:
  - port: prometheusport